### ISSUE TITLE
Klov 0.2.0 doesnt disable Redis session in configuration file

### ISSUE THREAD

**Issue by saymowan** [extent-framework/klov-server#1]
Using the new klov-0.2.0.jar with the same configuration of my old klov-0.1.1.jar: file _**application.properties**_  to disable the Redis session, it doesnt work.

This is the line that make it: `spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.session.SessionAutoConfiguration`

Below the file:
```
# extent-api
extent.api.version=pro

# klov
application.name=Klov
application.display.proLabels=false
server.port=899

# data.mongodb
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=klov

# data.rest
spring.data.rest.basePath=/rest
spring.data.rest.default-page-size=10

# redis, session
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.session.SessionAutoConfiguration
spring.session.store-type=redis
server.session.timeout=-1
spring.redis.host=localhost
spring.redis.port=6379

# users
server.admin.name=root
server.admin.key=$31$16$CO8q6Wj30ExE7RkD-nxwRkrLsQL2_sr2MpKQWfv3vPs

# storage
file.storage.location=./upload/reports/

# schedulers
scheduler.jobs.enabled=false
# automatically delete older builds
# default is -1 (keep all)
# this count must be greater than 0 for this scheduler to work
# scheduled to run daily at 12:00AM
scheduler.job.builds.retain.count=-1
```

Have something to change in the configuration file after the upgrade to klov 0.2.0 ? I dont want to use the Redis, only access my klov application without authentication like the old version.

Thanks!

**Comment by anshooarora** [comment]
This setting has changed, [here](https://github.com/extent-framework/klov-server/blob/master/0.2.0/application.properties) is the updated properties file.  Download the entire folder [here](https://github.com/extent-framework/klov-server/tree/master/0.2.0) and run using `java -jar klov.jar`.

**Comment by saymowan** [comment]
Thank you for replied @anshooarora .

The new **application.properties** file is working, but still requesting the Redis Authentication. 

I dont want to use the Redis authentication when I access my klov server, can you help me with this issue? Is there a command to input in the **application.properties** like the old version?

Look the main page here>
![xkaoukv](https://user-images.githubusercontent.com/6591115/48207022-e4326280-e356-11e8-830a-6ea947723c25.png)

**Comment by anshooarora** [comment]
You can download the 0.2.0 jar once again - it will get rid of the messages from the test-site.  

For Redis - ignore all the messages during startup, those are just for INFO.  Your session will start without Redis enabled.

**Comment by saymowan** [comment]
Yeah, I dit it.

My session started with Redis enabled using the new jar file.

Look this example of my server running with the klov 0.1.1 without sessions: http://automacaotestes.animaeducacao.com.br  

The problem of session Redis still happening with 0.2.0. localhost...

**Comment by anshooarora** [comment]
Hmm.. that is strange.  Do you have a redis server running on the same host as klov?  Default settings are `localhost:6379`.  

```
# redis, session
use.redis.session.store=false
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.ssl=false
spring.redis.database=0
spring.session.store-type=redis
server.session.timeout=-1
```

**Comment by anshooarora** [comment]
Ok - so, see my 1st reply.  Redis session is "disabled".  It is not using Redis session however in the startup logs, it will show INFO messages which mention that Redis is currently not enabled for certain models.  Ignore those messages.
