### ISSUE TITLE
when i update  the amdin user's password, system will pop error pages

### ISSUE THREAD

**Issue by touchsky211** [extent-framework/klov-server#4]

**Comment by foursyth** [comment]
Thank you,  I am able to reproduce.

**Comment by anshooarora** [comment]
This issue is due to an invalid route, points to `/account/` instead of `/user/`.   

Password will be changed though, just the redirect is broken.

**Comment by anshooarora** [comment]
Fix is already included in the upcoming version, will try to get in other fixes/enhancements and release after the new year.

**Comment by anshooarora** [comment]
Please use 0.2.3 - this issue is fixed.
