### ISSUE TITLE
Contact Info for pricing

### ISSUE THREAD

**Issue by divyashetti-cl** [extent-framework/klov-server#85]
Who do I contact to get pricing info for KLOV pro edition please?

**Comment by rado-o** [comment]
Hi,

I addressed the same problem in: https://github.com/extent-framework/klov/issues/75

**Klov Pro Edition**: demo page for Klov Pro as well as the link for getting  a license are returning errors:
@anshooarora : Could you please check it? Currently there is no possibility to check and/or buy the professional version.
It would be great to update the community version as well: I found a few bugs there, however, they could have been resolved in pro versions.

**Comment by divyashetti-cl** [comment]
Hi @rado-o 

Well, I did not hear back anything at all. So moved out of KLOV and implemented Allure Reporting. With all due respect to owner of Extent Reporting, my management team is very happy with Allure report because of the graphical representation and features it provides. It is very easy to implement and open source.
