### ISSUE TITLE
Klov docker documentation is not clear regarding mongodb

### ISSUE THREAD

**Issue by ValorHeart** [extent-framework/klov-server#87]
I assume that i need my own pre-installed mongodb, but does any configuration need to be make to the mongodb or install it as is and klov will create the database by itself ?

Thanks!

**Comment by chetanJTH** [comment]
you need docker too.

**Comment by ValorHeart** [comment]
> you need docker too.

Can you please elaborate ?

**Comment by ReGeorged** [comment]
> > you need docker too.
> 
> Can you please elaborate ?

You need an instance of mongo running in a docker as well, best way to do this is to use docker-compose and start with an instance of mongo and attach klov to it. a bit reply I know, I hope you already  had an answer for your question.

**Comment by ValorHeart** [comment]
Thanks, couple of years passed since my question and I've decided to move one with a difference solution since then.
